// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package container

import (
	"HomeWorkGo/infra/conf"
	"HomeWorkGo/infra/database"
	"HomeWorkGo/internal/repo"
	"HomeWorkGo/internal/service/wechat"
	"HomeWorkGo/internal/service/workflow"
)

// Injectors from wire.go:

func GetContainer(path string) *Container {
	config := conf.NewConfig(path)
	db := database.NewMySQL(config)
	iRepository := repo.NewRepository(db)
	iWechat := wechat.NewWeChat(iRepository)
	iWorkflow := workflow.NewWorkFlow(iRepository)
	container := NewContainer(iWechat, iWorkflow, config)
	return container
}
